export const JOB_TYPES = Object.freeze([
  "Alvenaria / Paredes",
  "AVAC / Climatização",
  "Canalização / Hidráulica",
  "Carpintaria / Madeiras",
  "Cerâmica / Azulejos",
  "Cobertura / Telhado",
  "Demolição",
  "Fachada / Revestimento Exterior",
  "Fundações / Betão Armado",
  "Gesso Cartonado",
  "Impermeabilização",
  "Instalações Elétricas",
  "Isolamento Acústico",
  "Isolamento Térmico",
  "Jardim / Arranjos Exteriores",
  "Pavimento / Betonilha",
  "Pintura Exterior",
  "Pintura Interior",
  "Reboco / Estuque",
  "Serralharia / Estruturas Metálicas",
  "Vãos / Portas / Janelas",
  "Outro",
]);

export const AREAS = Object.freeze([
  "Interior Geral",
  "Cave",
  "Rés-do-chão",
  "1.º Piso",
  "2.º Piso",
  "Cobertura / Terraço",
  "Hall / Corredor",
  "Escadas",
  "Sala",
  "Cozinha",
  "Suite",
  "Quarto 1",
  "Quarto 2",
  "Quarto 3",
  "Casa de Banho 1",
  "Casa de Banho 2",
  "Garagem",
  "Exterior",
  "Fachada Norte",
  "Fachada Sul",
  "Fachada Este",
  "Fachada Oeste",
  "Varanda",
  "Jardim",
  "Outro",
]);

export const STEP_NAMES = Object.freeze({
  period: "Período",
  3: "Progresso",
  4: "Resumo",
  5: "Trabalhos",
  6: "Fotos",
  7: "Decisão",
  8: "Incidentes",
  9: "Extras",
  10: "Financeiro",
  11: "Próximos Passos",
  12: "Revisão",
});

export const CONTENT_STEPS = Object.freeze({
  weekly: Object.freeze(["period", 3, 4, 5, 6, 7, 8, 11, 12]),
  legal: Object.freeze(["period", 9, 10, 12]),
});